### ISSUE TITLE
Tried to login but got Checkpoint Required

### ISSUE THREAD

**Issue by arisawali2014** [nsmle/igramapi#1]
When i try to login using my new instagram account. it says "Checkpoint required, please provide IMAP credentials to process authentication" how to solve this problem?

**Comment by nsmle** [comment]
I'm also still trying to solve this problem, this problem occurs on a remote server because instagram seems to detect the ip address and geo location of every incoming request.

When I tried it locally it worked fine. Maybe as an alternative I will add a method to login with Instagram cookies which can be retrieved by following the tutorial [here](https://wpautomatic.com/how-to-get-instagram-session-id/).

Maybe the [pgrimaud/instagram-user-feed discussion #87](https://github.com/pgrimaud/instagram-user-feed/issues/87) can help, since most of these repo rely on the above libraries.

Or if you have ideas and solutions to solve this problem, [PR](https://github.com/nsmle/igramapi/pulls) will always be open. Check progress on branch [fix/checkpoint](https://github.com/nsmle/igramapi/tree/fix/checkpoint) and join to solve this problem together😊

**Comment by arisawali2014** [comment]
i think the better way is to implement other method that can choose wether use Email or Number to send a security code. then manually enter the code. 
when i check the code i don't know how you make a new routing for the plugins XD

**Comment by nsmle** [comment]
Great idea, but I'm not sure about it and it looks like it would be the same.

I used [laravel](https://laravel.com/docs/9.x/structure) to build this and All api routes are defined in [routes/api.php](https://github.com/nsmle/igramapi/blob/main/routes/api.php) with api controller defined in [app/Http/Controllers/Api/](https://github.com/nsmle/igramapi/tree/main/app/Http/Controllers/Api)

**Comment by arisawali2014** [comment]
how about the instagrama endpoint there. i didn't see it at the routes/api.php

**Comment by nsmle** [comment]
Maybe you can take a look at the [pgrimaud/instagram-user-feed](https://github.com/pgrimaud/instagram-user-feed) library first to understand how I use it here.

I overridden and added some custom methods from [pgrimaud/instagram-user-feed](https://github.com/pgrimaud/instagram-user-feed/blob/master/src/Instagram/Api.php) which you can find in the [app/Repositories/InstagramRepository.php](https://github.com/nsmle/igramapi/blob/main/app/Repositories/InstagramRepository.php) class and implemented them with JWT in the [app/Services/InstagramService.php](https://github.com/nsmle/igramapi/blob/main/app/Services/InstagramService.php) class which is used throughout the [app/Http/Controllers/Api/](https://github.com/nsmle/igramapi/tree/main/app/Http/Controllers/Api) api controllers
